export const carouselData = [
  {
    name: 'Pearl River Resort',
    imgUrl: './sponsors/pearlriver2.png',
    imgClass: 'platinum',
    linkUrl: 'https://www.pearlriverresort.com',
  },
  {
    name: 'Merchants Food Server',
    imgUrl: './sponsors/merchants.png',
    imgClass: 'platinum',
    linkUrl: 'https://merchantsfoodservice.com',
  },
  {
    name: 'Yates',
    imgUrl: './sponsors/yates.png',
    imgClass: 'platinum',
    linkUrl: 'https://yates.doitbest.com',
  },
  {
    name: 'Pryor Morrow',
    imgUrl: './sponsors/pryormorrow.png',
    imgClass: 'platinum',
    linkUrl: 'https://pryormorrow.com',
  },
  {
    name: 'Trustmark Bank',
    imgUrl: './sponsors/trustmark.png',
    imgClass: 'platinum',
    linkUrl: 'https://www.trustmark.com',
  },
  {
    name: 'Walt Schrimpf (SIS-UNUM)',
    imgUrl: './sponsors/sis.png',
    imgClass: 'platinum',
    linkUrl: 'https://www.unum.com',
  },
  {
    name: 'Pearl River Resort',
    imgUrl: './sponsors/pearlriver2.png',
    imgClass: 'platinum',
    linkUrl: 'https://www.pearlriverresort.com',
  },
  {
    name: 'Merchants Food Server',
    imgUrl: './sponsors/merchants.png',
    imgClass: 'platinum',
    linkUrl: 'https://merchantsfoodservice.com',
  },
  {
    name: 'Yates',
    imgUrl: './sponsors/yates.png',
    imgClass: 'platinum',
    linkUrl: 'https://yates.doitbest.com',
  },
  {
    name: 'Pryor Morrow',
    imgUrl: './sponsors/pryormorrow.png',
    imgClass: 'platinum',
    linkUrl: 'https://pryormorrow.com',
  },
  {
    name: 'Trustmark Bank',
    imgUrl: './sponsors/trustmark.png',
    imgClass: 'platinum',
    linkUrl: 'https://www.trustmark.com',
  },
  {
    name: 'Walt Schrimpf (SIS-UNUM)',
    imgUrl: './sponsors/sis.png',
    imgClass: 'platinum',
    linkUrl: 'https://www.unum.com',
  },
  {
    name: 'Pearl River Resort',
    imgUrl: './sponsors/pearlriver2.png',
    imgClass: 'platinum',
    linkUrl: 'https://www.pearlriverresort.com',
  },
  {
    name: 'Merchants Food Server',
    imgUrl: './sponsors/merchants.png',
    imgClass: 'platinum',
    linkUrl: 'https://merchantsfoodservice.com',
  },
  {
    name: 'Yates',
    imgUrl: './sponsors/yates.png',
    imgClass: 'platinum',
    linkUrl: 'https://yates.doitbest.com',
  },
  {
    name: 'Pryor Morrow',
    imgUrl: './sponsors/pryormorrow.png',
    imgClass: 'platinum',
    linkUrl: 'https://pryormorrow.com',
  },
  {
    name: 'Trustmark Bank',
    imgUrl: './sponsors/trustmark.png',
    imgClass: 'platinum',
    linkUrl: 'https://www.trustmark.com',
  },
  {
    name: 'Walt Schrimpf (SIS-UNUM)',
    imgUrl: './sponsors/sis.png',
    imgClass: 'platinum',
    linkUrl: 'https://www.unum.com',
  },
]
